### ISSUE TITLE
Doesn't jump

### ISSUE THREAD

**Issue by aderchox** [tranhl/find-then-jump#48] opened 2022-08-28 18:42 UTC
It doesn't jump:
![demo](https://user-images.githubusercontent.com/52244768/187089725-7ea333b8-c81c-4003-b09d-06441054bede.gif)

**Comment by tranhl** [comment] 2022-10-27 00:02
@aderchox a jump is triggered when you type in the character for the associated jumping point. Because the characters are displayed as text decorations, it's not possible to jump to code outside of the visible editor view. If you want to go to code that isn't visible, use the editor's built in find functionality.

Closing as this is not a bug.

**Closed by tranhl** 2022-10-27 00:02 UTC
